# Generated by Django 5.0.4 on 2024-04-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='flag',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
