# Generated by Django 5.0.4 on 2024-04-20 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_item_dyn_price_strat_item_comp_price_item_eco_ind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cat',
            field=models.CharField(choices=[('Electronics', 0), ('Home Appliances', 1), ('Clothing', 2), ('Health & Beauty', 3), ('Books', 4)], max_length=30),
        ),
    ]
