# Generated by Django 5.0.4 on 2024-04-20 23:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_item_cat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="Dyn_price_strat",
            field=models.IntegerField(
                choices=[
                    ("Dynamic Bundling", 0),
                    ("Dynamic Markdowns", 1),
                    ("Personalized Pricing", 2),
                    ("Discounting", 3),
                ],
                default=2,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="cat",
            field=models.IntegerField(
                choices=[
                    ("Electronics", 0),
                    ("Home Appliances", 1),
                    ("Clothing", 2),
                    ("Health & Beauty", 3),
                    ("Books", 4),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="seasonality",
            field=models.IntegerField(choices=[("Low", 0), ("Medium", 1), ("High", 2)]),
        ),
        migrations.AlterField(
            model_name="item",
            name="sentiment",
            field=models.IntegerField(
                choices=[("Negative", -1), ("Neutral", 0), ("Positive", 1)], default=0
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="flag",
            field=models.IntegerField(
                choices=[("Inactive", 0), ("New", 1), ("Regular", 2), ("Premium", 3)],
                default=1,
            ),
        ),
    ]
