# Generated by Django 5.0.4 on 2024-04-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_item_dyn_price_strat_alter_item_cat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="Dyn_price_strat",
            field=models.CharField(
                choices=[
                    ("Dynamic Bundling", 0),
                    ("Dynamic Markdowns", 1),
                    ("Personalized Pricing", 2),
                    ("Discounting", 3),
                ],
                default="Personalized Pricing",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="cat",
            field=models.CharField(
                choices=[
                    ("Electronics", 0),
                    ("Home Appliances", 1),
                    ("Clothing", 2),
                    ("Health & Beauty", 3),
                    ("Books", 4),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="seasonality",
            field=models.CharField(
                choices=[("Low", 0), ("Medium", 1), ("High", 2)], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="sentiment",
            field=models.CharField(
                choices=[("Negative", -1), ("Neutral", 0), ("Positive", 1)],
                default="Neutral",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="flag",
            field=models.CharField(
                choices=[("Inactive", 0), ("New", 1), ("Regular", 2), ("Premium", 3)],
                default="New",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=200),
        ),
    ]
